version: '3.4'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    ports: 
        - "15672:15472"
        - "5672:5672"
    labels:
        NAME: "some-rabbit"
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment: 
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "pa55w0rd!"
        MSSQL_PID: "Express"
    ports:
        - "1433:1433"    
  travelagentweb:
    image: ${DOCKER_REGISTRY-}travelagentweb
    build:
      context: .
      dockerfile: TravelAgentWeb\Dockerfile
   