version: '3.4'

services:
  travelagentweb:
    image: travelagentweb:dev
    container_name: TravelAgentWeb
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "TravelAgentWeb"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_travelagentweb$
    volumes:
      - C:\Users\SIMPLEX644\Desktop\apps\dotnet\AirlineWeb\TravelAgentWeb:C:\app
      - C:\Users\SIMPLEX644\Desktop\apps\dotnet\AirlineWeb:C:\src
      - C:\Users\SIMPLEX644\onecoremsvsmon\17.3.10630.1389:C:\remote_debugger:ro
#$nuget_volume_mapping_travelagentweb$
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro

    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646 /LogDebuggeeOutputToStdOut
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_travelagentweb$ \"C:\\src\\..\\..\\..\\..\\source\\repos\\AirlineWeb\\TravelAgentWeb\\bin\\Debug\\net5.0\\TravelAgentWeb.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"
